### ISSUE TITLE
urban command assumes that each index of the tuple that contains that user inputs is never more than 1 word

### ISSUE THREAD

**Issue by TitanVJ** [CSSS/wall_e#156]
if search query has space the link messes up.

ex: https://discordapp.com/channels/228761314644852736/228761314644852736/545863249866784788

**Comment by TitanVJ** [comment]
bug occurs with ""

**Comment by modernNeo** [comment]
to be more clear with what the error is, when the urban command takes in the arguments, it is taking in a tuple and assuming that each tuples contains only 1 word, which is the case when calling it like so `.urban trump suck`.  
  
But should someone call the command like this `.urban "trump sucks"`, "trump" and "sucks" both end up in the first index of the tuple like so `('trump sucks',)` which the command assumes is one word rather than 2. this requires checking each entry for a space and replacing that space with `%20`.

**Comment by modernNeo** [comment]
@TitanVJ in the future, it doesnt hurt to be more verbose with the error like I have done above. just helps for historic and readability reasons.

**Comment by modernNeo** [comment]
faulty code being here https://github.com/CSSS/wall_e/blob/a51e99b81eb9e0db2a8d44d1cc0de92adfbdc3c1/commands_to_load/Misc.py#L75-L76

**Comment by modernNeo** [comment]
something like this should be enough .  
`queryString += x.replace(' ', '%20') + '%20'`

**Comment by modernNeo** [comment]
being handled with PR https://github.com/CSSS/wall_e/pull/179

**Comment by modernNeo** [comment]
being handled with PR https://github.com/CSSS/wall_e/pull/187
