### ISSUE TITLE
implement pruning

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#158]
make sure that the jenkins is setup to prune any unused images, containers, volumes, networks or databases

**Comment by modernNeo** [comment]
this one will be handled after the Ci/CD has been fixed by @modernNeo and @wnfldchen

**Comment by modernNeo** [comment]
first PR that is involved is https://github.com/CSSS/wall_e/pull/192

**Comment by wnfldchen** [comment]
In the meantime, I just set up a cron job which should do `docker image prune -f; docker volume prune -f` every day in the early morning, which should keep it clean. When it ran today it removed about 9 GB of old images and volumes, reducing our disk usage from 90% to 55%. I do very much like the cronjob solution due to its simplicity, and infallibility.

**Comment by modernNeo** [comment]
@wnfldchen do you think its more appropriate to put in it in a cronjob that will run every day even when it is not necessary or to put it in one of the `wall-e-clean` or `wall-e-clean-pr` jobs that will only run it when it is needed? I though the latter would be a "cleaner" approach

**Comment by modernNeo** [comment]
@wnfldchen just to be clear, I am not saying your current solution is a bad one. It works well as a temporary solution. I am just saying that long-term, I feel like it should be changed for what I suggested above?

**Comment by wnfldchen** [comment]
I think we should look at putting it into the cleaning jobs. We'll have to be careful about how we do it. I think if it can be pulled off, it would be nice in the long run.

**Comment by modernNeo** [comment]
fixed with https://jenkins.sfucsss.org/job/clean%20docker%20resources/
